version: "3.9"
services:
  reverseproxy:
    image: reverseproxy
    ports:
        - 8081:8081
    restart: always
  nginx:
    depends_on:
        - reverseproxy
    image: nginx:alpine
    restart: always
  tutorijal6:
    image: "getting-started"
    ports:
      - "3000:3000"
  prvi:
    image: "prvi"
    ports:
        - "8080:8080"
    